name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install uv
          uv sync --group test
      - name: Run tests
        run: uv run pytest
  docker:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: mode=max
          sbom: true
          platforms: linux/amd64,linux/arm64
          tags: bearda/potatastic:latest
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/bearda/potatastic
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true